-- PROCEDURE: property.create_mv_property_vinculum()

-- DROP PROCEDURE IF EXISTS property.create_mv_property_vinculum();

CREATE OR REPLACE PROCEDURE property.create_mv_property_vinculum(
	)
LANGUAGE 'sql'
AS $BODY$
DROP MATERIALIZED VIEW IF EXISTS property.property_vinculum CASCADE;

CREATE MATERIALIZED VIEW property.property_vinculum
TABLESPACE pg_default
AS

-- ----------------------------------
-- Property Vinculum < 500m
-- indicates that two or more physically separated areas of land belong to and form a single, unified property
-- ----------------------------------
WITH exploded AS (
    SELECT row_number() OVER (ORDER BY (ST_Dump(geom)).geom) AS fid,
        prop_no,
        (ST_Dump(geom)).geom AS geom,
		geom AS prop_geom
    FROM property.property
)
SELECT 
    row_number() OVER (ORDER BY a.prop_no) AS fid,
    a.prop_no,
    ST_Difference(ST_ShortestLine(ST_PointOnSurface(a.geom), ST_PointOnSurface(b.geom)),a.prop_geom) AS geom
FROM exploded a
JOIN exploded b
    ON a.prop_no = b.prop_no
   AND a.fid < b.fid
   AND ST_Length(ST_ShortestLine(ST_Centroid(a.geom), ST_Centroid(b.geom))) < 500

WITH DATA;

ALTER TABLE property.property_vinculum
    OWNER TO postgres;

GRANT ALL ON TABLE property.property_vinculum TO postgres;
GRANT ALL ON TABLE property.property_vinculum TO wdc;
GRANT SELECT ON TABLE property.property_vinculum TO wdc_gisprod;

CREATE INDEX property_vinculum_polygons_fid_idx
    ON property.property_vinculum USING btree(fid)
    TABLESPACE pg_default;
CREATE INDEX property_vinculum_polygons_prop_no_idx
    ON property.property_vinculum USING btree(prop_no)
    TABLESPACE pg_default;
CREATE INDEX property_vinculum_polygons_geom_idx
    ON property.property_vinculum USING gist(geom)
    TABLESPACE pg_default;

DO
$do$
BEGIN
EXECUTE format($$COMMENT ON MATERIALIZED VIEW property.property_vinculum is 'Regenerated by Stored Procedure %s'$$, LOCALTIMESTAMP);
END
$do$
$BODY$;

ALTER PROCEDURE property.create_mv_property_vinculum()
    OWNER TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_vinculum() TO PUBLIC;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_vinculum() TO postgres;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_vinculum() TO wdc;

GRANT EXECUTE ON PROCEDURE property.create_mv_property_vinculum() TO wdc_gisprod;

